# docker-compose.yml
#version: '3.8'

services:
  fintech-dashboard-backend:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URI=mysql+pymysql://user:password@db/dbname
      - API_KEY=your_api_key_here

  fintech-dashboard-frontend:
    build: ./app/ui
    ports:
      - "8000:8000"
